project_id = "xbonrxqrzkuwxovyqrxx"

[functions.pubmed-integration]
verify_jwt = false

[functions.cochrane-integration]
verify_jwt = false

[functions.pedro-integration]
verify_jwt = false

[functions.guidelines-integration]
verify_jwt = false

[functions.evidence-sync]
verify_jwt = false

[functions.generate-assessment-tools]
verify_jwt = false

[functions.generate-condition-protocols]
verify_jwt = false

[functions."generate-condition-protocols".limits]
cpu_ms = 150000
memory_mb = 512

[functions.clone-protocol]
verify_jwt = true

[functions.populate-nice-guidelines]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false
