project_id = "xbonrxqrzkuwxovyqrxx"

[functions.pubmed-integration]
verify_jwt = false

[functions.cochrane-integration]
verify_jwt = false

[functions.pedro-integration]
verify_jwt = false

[functions.guidelines-integration]
verify_jwt = false

[functions.evidence-sync]
verify_jwt = false

[functions.generate-assessment-tools]
verify_jwt = false

[functions.generate-condition-protocols]
verify_jwt = false
