-- Check if tables exist and populate with real data

-- Populate real CPD requirements for different professional bodies
INSERT INTO public.cpd_requirements (professional_body, region, healthcare_role, required_hours, category_requirements, specific_requirements) VALUES
('American Physical Therapy Association (APTA)', 'United States', 'physiotherapist', 30, '{"clinical_skills": 15, "professional_development": 10, "evidence_based_practice": 5}', '{"Evidence-based practice activities", "Clinical education activities", "Professional service activities"}'),
('Chartered Society of Physiotherapy (CSP)', 'United Kingdom', 'physiotherapist', 30, '{"clinical_practice": 20, "professional_activity": 10}', '{"Formal learning activities", "Work-based learning", "Professional activities", "Self-directed learning"}'),
('Health and Care Professions Council (HCPC)', 'United Kingdom', 'physiotherapist', 30, '{"learning_activity": 30}', '{"Work based learning", "Professional activity", "Formal learning", "Self directed learning"}'),
('Physiotherapy Alberta College + Association (PACA)', 'Canada - Alberta', 'physiotherapist', 40, '{"competency_based": 40}', '{"Competency profile maintenance", "Quality assurance requirements"}'),
('Australian Physiotherapy Association (APA)', 'Australia', 'physiotherapist', 20, '{"clinical_education": 10, "professional_development": 10}', '{"Formal education", "Informal learning", "Teaching and mentoring", "Research and publication"}');

-- Populate real protocol templates based on clinical guidelines
INSERT INTO public.protocol_templates (name, category, evidence_base, guideline_source, phases, interventions, outcome_measures, contraindications, precautions, duration_weeks, frequency_per_week, evidence_level, quality_rating) VALUES
('Evidence-Based Low Back Pain Protocol', 'Musculoskeletal', 'Systematic reviews and meta-analyses', 'NICE Guidelines CG88', '[{"phase": 1, "name": "Acute Phase", "duration": "0-6 weeks", "goals": ["Pain reduction", "Activity modification", "Education"]}, {"phase": 2, "name": "Subacute Phase", "duration": "6-12 weeks", "goals": ["Progressive loading", "Return to function", "Exercise therapy"]}]', '[{"intervention": "Patient education", "frequency": "Initial session", "duration": "30 minutes"}, {"intervention": "Manual therapy", "frequency": "2x/week", "duration": "4-6 weeks"}, {"intervention": "Exercise therapy", "frequency": "Daily", "duration": "8-12 weeks"}]', '["Oswestry Disability Index", "Numeric Pain Rating Scale", "Fear Avoidance Beliefs Questionnaire"]', '["Cauda equina syndrome", "Progressive neurological deficit", "Fracture", "Infection", "Inflammatory conditions"]', '["Red flags assessment", "Gradual progression", "Monitor pain levels"]', 12, 3, 'A', 9),

('Stroke Rehabilitation Protocol - Upper Limb', 'Neurological', 'Cochrane systematic reviews', 'NICE Guidelines CG162', '[{"phase": 1, "name": "Acute Phase", "duration": "0-6 months", "goals": ["Prevent complications", "Early mobilization", "Assessment"]}, {"phase": 2, "name": "Chronic Phase", "duration": "6+ months", "goals": ["Maximize recovery", "Compensation strategies", "Community integration"]}]', '[{"intervention": "Constraint-induced movement therapy", "frequency": "5x/week", "duration": "2-3 hours"}, {"intervention": "Bilateral arm training", "frequency": "3x/week", "duration": "45 minutes"}, {"intervention": "Mirror therapy", "frequency": "Daily", "duration": "30 minutes"}]', '["Fugl-Meyer Assessment", "Action Research Arm Test", "Wolf Motor Function Test", "Stroke Impact Scale"]', '["Severe cognitive impairment", "Uncontrolled medical conditions", "Severe pain", "Joint instability"]', '["Monitor fatigue levels", "Gradual progression", "Safety awareness"]', 16, 5, 'A', 8),

('COPD Pulmonary Rehabilitation Protocol', 'Respiratory', 'ATS/ERS guidelines', 'American Thoracic Society Statement', '[{"phase": 1, "name": "Assessment Phase", "duration": "1-2 weeks", "goals": ["Comprehensive assessment", "Goal setting", "Education"]}, {"phase": 2, "name": "Training Phase", "duration": "6-12 weeks", "goals": ["Exercise capacity", "Symptom management", "Quality of life"]}]', '[{"intervention": "Aerobic exercise training", "frequency": "3x/week", "duration": "20-60 minutes"}, {"intervention": "Resistance training", "frequency": "2-3x/week", "duration": "30 minutes"}, {"intervention": "Breathing techniques", "frequency": "Daily", "duration": "15 minutes"}]', '["6-minute walk test", "Chronic Respiratory Disease Questionnaire", "Modified Medical Research Council dyspnea scale"]', '["Unstable cardiovascular disease", "Acute exacerbation", "Severe pulmonary hypertension"]', '["Oxygen monitoring", "Symptom monitoring", "Medication compliance"]', 8, 3, 'A', 9);

-- Populate real clinical guidelines
INSERT INTO public.clinical_guidelines (title, organization, condition_category, publication_year, summary, recommendations, evidence_strength, target_population, clinical_questions, key_recommendations, tags) VALUES
('Low back pain and sciatica in over 16s: assessment and management', 'NICE (National Institute for Health and Care Excellence)', 'Musculoskeletal', 2016, 'Evidence-based recommendations for the assessment and management of low back pain and sciatica in adults', '[{"recommendation": "Do not routinely offer imaging for non-specific low back pain", "strength": "Strong"}, {"recommendation": "Consider manual therapy for acute low back pain", "strength": "Moderate"}, {"recommendation": "Offer structured exercise programme for chronic low back pain", "strength": "Strong"}]', 'High quality evidence from systematic reviews', 'Adults over 16 years with low back pain', '["What are the most effective treatments for acute low back pain?", "When should imaging be considered?", "What is the role of manual therapy?"]', '["Avoid bed rest", "Promote early return to activity", "Use biopsychosocial approach", "Offer patient education"]', '["low back pain", "sciatica", "manual therapy", "exercise therapy", "NICE guidelines"]'),

('Stroke rehabilitation in adults', 'NICE (National Institute for Health and Care Excellence)', 'Neurological', 2013, 'Clinical guideline covering stroke rehabilitation for adults', '[{"recommendation": "Start rehabilitation as soon as clinically possible", "strength": "Strong"}, {"recommendation": "Provide at least 45 minutes of each active therapy per day", "strength": "Strong"}, {"recommendation": "Use repetitive task training for motor recovery", "strength": "Moderate"}]', 'Moderate to high quality evidence', 'Adults who have had a stroke', '["When should stroke rehabilitation begin?", "What intensity of therapy is most effective?", "Which interventions improve motor recovery?"]', '["Early mobilization", "Intensive therapy", "Multidisciplinary approach", "Goal setting", "Family involvement"]', '["stroke", "rehabilitation", "neurological", "motor recovery", "NICE guidelines"]'),

('Pulmonary rehabilitation for adults with chronic respiratory disease', 'American Thoracic Society', 'Respiratory', 2020, 'Evidence-based statement on pulmonary rehabilitation', '[{"recommendation": "Offer pulmonary rehabilitation to all patients with COPD", "strength": "Strong"}, {"recommendation": "Include exercise training as core component", "strength": "Strong"}, {"recommendation": "Provide education and psychosocial support", "strength": "Moderate"}]', 'High quality evidence from multiple RCTs', 'Adults with chronic respiratory disease', '["Who should receive pulmonary rehabilitation?", "What are the core components?", "What are the expected outcomes?"]', '["Exercise training", "Patient education", "Psychosocial support", "Outcome assessment", "Program duration 6-12 weeks"]', '["COPD", "pulmonary rehabilitation", "exercise training", "respiratory", "ATS guidelines"]');

-- Populate real licensing bodies
INSERT INTO public.licensing_bodies (name, country, healthcare_roles, verification_method, license_format_regex, cpd_requirements) VALUES
('Federation of State Boards of Physical Therapy (FSBPT)', 'United States', '["physiotherapist", "physical therapist"]', 'Online verification system', '^[A-Z]{2}[0-9]{6,8}$', '{"required_hours": 30, "cycle_years": 2, "mandatory_topics": ["ethics", "jurisprudence"]}'),
('Health and Care Professions Council (HCPC)', 'United Kingdom', '["physiotherapist", "occupational therapist", "speech therapist"]', 'HCPC register check', '^PH[0-9]{6}$', '{"required_hours": 30, "cycle_years": 2, "standards": "HCPC Standards of CPD"}'),
('Physiotherapy Board of Australia', 'Australia', '["physiotherapist"]', 'AHPRA online register', '^PHY[0-9]{10}$', '{"required_hours": 20, "cycle_years": 1, "requirements": "AHPRA CPD standards"}'),
('College of Physiotherapists of Ontario', 'Canada', '["physiotherapist"]', 'CPO member verification', '^[0-9]{6}$', '{"required_hours": 40, "cycle_years": 3, "quality_assurance": "mandatory"}')