-- Populate Conditions with comprehensive musculoskeletal, neurological, and respiratory conditions
INSERT INTO public.conditions (name, category, description, icd_codes, keywords, prevalence_data) VALUES
-- Musculoskeletal Conditions
('Low Back Pain', 'msk', 'Pain and discomfort in the lower back region, often caused by muscle strain, disc problems, or postural issues. Most common musculoskeletal complaint in clinical practice.', ARRAY['M54.5', 'M54.50', 'M54.51'], ARRAY['back pain', 'lumbar', 'spine', 'disc', 'sciatica'], '{"global_prevalence": "23%", "annual_incidence": "12%", "lifetime_prevalence": "84%", "peak_age": "40-80"}'),
('Neck Pain', 'msk', 'Cervical spine pain often associated with poor posture, whiplash, or degenerative changes. Common in office workers and post-trauma patients.', ARRAY['M54.2', 'M54.20'], ARRAY['cervical', 'neck', 'whiplash', 'posture', 'cervicalgia'], '{"global_prevalence": "15%", "annual_incidence": "8%", "peak_age": "35-55", "gender_ratio": "2:1 female"}'),
('Knee Osteoarthritis', 'msk', 'Degenerative joint disease affecting the knee, characterized by cartilage breakdown and pain. Leading cause of disability in older adults.', ARRAY['M17.0', 'M17.1', 'M17.9'], ARRAY['arthritis', 'knee', 'cartilage', 'joint', 'degenerative'], '{"global_prevalence": "3.8%", "age_65+": "10%", "gender_ratio": "1.7:1 female", "disability_rank": "11th globally"}'),
('Shoulder Impingement', 'msk', 'Compression of rotator cuff tendons causing pain and restricted movement. Common in overhead athletes and manual workers.', ARRAY['M75.3', 'M75.30'], ARRAY['shoulder', 'rotator cuff', 'impingement', 'overhead', 'subacromial'], '{"prevalence": "5-25%", "peak_age": "40-60", "occupation_risk": "overhead workers", "athlete_prevalence": "30%"}'),
('Tennis Elbow', 'msk', 'Lateral epicondylitis causing pain on the outer elbow, typically from repetitive wrist and arm motions.', ARRAY['M77.1', 'M77.10'], ARRAY['tennis elbow', 'lateral epicondylitis', 'elbow', 'tendonitis'], '{"prevalence": "1-3%", "peak_age": "35-50", "occupation_risk": "manual labor", "sports_risk": "racquet sports"}'),
('Plantar Fasciitis', 'msk', 'Inflammation of the plantar fascia causing heel pain, especially with first steps in the morning.', ARRAY['M72.2'], ARRAY['heel pain', 'plantar fascia', 'foot', 'fascitis'], '{"prevalence": "10%", "peak_age": "40-60", "risk_factors": "obesity, running", "bilateral": "30%"}'),

-- Neurological Conditions  
('Stroke', 'neurological', 'Cerebrovascular accident resulting in brain tissue damage, leading to various neurological deficits including motor, sensory, and cognitive impairments.', ARRAY['I63.9', 'I64', 'I61.9'], ARRAY['stroke', 'CVA', 'hemiplegia', 'cerebrovascular', 'brain'], '{"global_incidence": "13.7M/year", "prevalence": "80M", "mortality_rank": "2nd", "disability_rank": "3rd"}'),
('Multiple Sclerosis', 'neurological', 'Autoimmune demyelinating disease of the central nervous system causing progressive neurological dysfunction.', ARRAY['G35'], ARRAY['MS', 'multiple sclerosis', 'demyelinating', 'autoimmune', 'CNS'], '{"global_prevalence": "2.8M", "peak_age": "20-40", "gender_ratio": "3:1 female", "geographic_variation": "higher latitudes"}'),
('Parkinsons Disease', 'neurological', 'Progressive neurodegenerative disorder affecting movement, characterized by tremor, rigidity, and bradykinesia.', ARRAY['G20'], ARRAY['parkinsons', 'tremor', 'rigidity', 'bradykinesia', 'dopamine'], '{"global_prevalence": "6.1M", "age_60+": "1%", "incidence": "increasing", "gender_ratio": "1.5:1 male"}'),
('Spinal Cord Injury', 'neurological', 'Damage to the spinal cord resulting in temporary or permanent changes in function, sensation, and movement.', ARRAY['S14.109A', 'T09.3'], ARRAY['SCI', 'paraplegia', 'quadriplegia', 'spinal cord'], '{"global_incidence": "250,000-500,000/year", "peak_age": "16-30", "gender_ratio": "4:1 male", "causes": "trauma 90%"}'),
('Traumatic Brain Injury', 'neurological', 'Brain dysfunction caused by external force, ranging from mild concussion to severe brain damage.', ARRAY['S06.9', 'S06.00'], ARRAY['TBI', 'concussion', 'brain injury', 'head trauma'], '{"global_incidence": "69M/year", "peak_age": "15-24, 65+", "gender_ratio": "2:1 male", "mild_TBI": "75%"}'),
('Peripheral Neuropathy', 'neurological', 'Damage to peripheral nerves causing weakness, numbness, and pain, often in hands and feet.', ARRAY['G62.9', 'E11.40'], ARRAY['neuropathy', 'peripheral nerves', 'diabetic', 'numbness'], '{"prevalence": "2.4%", "diabetes_related": "50%", "age_40+": "8%", "causes": "diabetes, alcohol, chemo"}'),

-- Respiratory Conditions
('Chronic Obstructive Pulmonary Disease', 'respiratory', 'Progressive lung disease characterized by airflow limitation, including emphysema and chronic bronchitis.', ARRAY['J44.0', 'J44.1'], ARRAY['COPD', 'emphysema', 'chronic bronchitis', 'airflow limitation'], '{"global_prevalence": "251M", "mortality_rank": "3rd", "gender_ratio": "equal", "smoking_related": "85%"}'),
('Asthma', 'respiratory', 'Chronic inflammatory airway disease causing reversible airflow obstruction and bronchial hyperresponsiveness.', ARRAY['J45.9', 'J45.0'], ARRAY['asthma', 'bronchial', 'wheezing', 'inflammatory'], '{"global_prevalence": "339M", "children": "14%", "adults": "8.6%", "increasing_trend": "yes"}'),
('Pneumonia', 'respiratory', 'Infection causing inflammation in lung air sacs, which may fill with fluid or pus, causing breathing difficulties.', ARRAY['J18.9', 'J15.9'], ARRAY['pneumonia', 'lung infection', 'respiratory infection'], '{"global_incidence": "450M/year", "mortality": "4M/year", "children_u5": "15%", "adults_65+": "high risk"}'),
('Pulmonary Fibrosis', 'respiratory', 'Scarring and thickening of lung tissue, making breathing increasingly difficult over time.', ARRAY['J84.10', 'J84.112'], ARRAY['pulmonary fibrosis', 'lung scarring', 'IPF', 'interstitial'], '{"prevalence": "3M globally", "peak_age": "50-75", "gender_ratio": "2:1 male", "prognosis": "2-5 years"}'),
('Cystic Fibrosis', 'respiratory', 'Genetic disorder affecting lungs and digestive system, causing thick, sticky mucus production.', ARRAY['E84.0', 'E84.9'], ARRAY['cystic fibrosis', 'CF', 'genetic', 'mucus'], '{"prevalence": "70,000 globally", "carrier_rate": "1:25", "median_age": "40+ years", "genetic": "CFTR mutation"}'),
('Sleep Apnea', 'respiratory', 'Sleep disorder characterized by repeated breathing interruptions during sleep, affecting oxygen levels.', ARRAY['G47.33', 'G47.30'], ARRAY['sleep apnea', 'OSA', 'breathing', 'snoring'], '{"prevalence": "936M globally", "men": "13%", "women": "6%", "obesity_related": "strong association"}')